
import type { TranslationData } from './types';

export const translations: TranslationData = {
  en: {
    // Header & Footer
    language_switcher: 'DE',
    footer_text: 'Built for modern web analysis.',
    // Main page
    main_headline: 'Instant Website Health Audit',
    main_subheadline: 'Enter your URL to receive a comprehensive performance, SEO, and accessibility report in seconds. Free and easy.',
    placeholder_url: 'Enter your website URL (e.g., vercel.com)',
    button_analyze: 'Analyze',
    button_analyzing: 'Analyzing...',
    // Loader
    loader_text: 'Auditing your site... this may take a moment.',
    // Errors
    error_message: 'Failed to analyze the website. The URL may be invalid, unreachable, or the service is temporarily down. Please check the URL and try again.',
    error_unknown: 'An unknown error occurred.',
    error_title: 'Analysis Failed',
    // Dashboard
    dashboard_title: 'Audit Report for',
    download_pdf: 'Download PDF',
    overall_scores: 'Overall Scores',
    performance: 'Performance',
    accessibility: 'Accessibility',
    best_practices: 'Best Practices',
    seo: 'SEO',
    core_web_vitals: 'Core Web Vitals',
    lcp: 'Largest Contentful Paint',
    lcp_desc: 'Time for the largest content element to become visible.',
    cls: 'Cumulative Layout Shift',
    cls_desc: 'Measures visual stability of the page.',
    inp: 'Interaction to Next Paint',
    inp_desc: 'Measures page responsiveness to user interactions.',
    key_metrics: 'Key Metrics',
    fcp: 'First Contentful Paint',
    fcp_desc: 'Time for the first piece of content to appear.',
    speed_index: 'Speed Index',
    speed_index_desc: 'How quickly content is visually displayed.',
    tti: 'Time to Interactive',
    tti_desc: 'Time until the page is fully interactive.',
    tbt: 'Total Blocking Time',
    tbt_desc: 'Time the main thread was blocked.',
    server_response_time: 'Server Response Time',
    server_response_time_desc: 'Time for the server to respond (TTFB).',
    https: 'Uses HTTPS',
    https_desc: 'Ensures a secure connection.',
    crawlable: 'Is Crawlable',
    crawlable_desc: 'Search engines can access the site.',
    mobile_friendly: 'Mobile Friendly',
    mobile_friendly_desc: 'Has a viewport meta tag for mobile.',
    readable_fonts: 'Readable Fonts',
    readable_fonts_desc: 'Font sizes are large enough for legibility.',
    image_aspect_ratio: 'Correct Image Aspect Ratio',
    image_aspect_ratio_desc: 'Images have correct width/height attributes.',
    page_stats: 'Page Statistics',
    total_page_size: 'Total Page Size',
    total_requests: 'Total Requests',
    js_execution_time: 'JS Execution Time',
    pass: 'Pass',
    fail: 'Fail'
  },
  de: {
    // Header & Footer
    language_switcher: 'EN',
    footer_text: 'Gebaut für moderne Web-Analyse.',
    // Main page
    main_headline: 'Sofortige Website-Zustandsprüfung',
    main_subheadline: 'Geben Sie Ihre URL ein, um in Sekunden einen umfassenden Bericht zu Leistung, SEO und Barrierefreiheit zu erhalten. Kostenlos und einfach.',
    placeholder_url: 'Ihre Website-URL eingeben (z.B. vercel.com)',
    button_analyze: 'Analysieren',
    button_analyzing: 'Analysiere...',
    // Loader
    loader_text: 'Ihre Seite wird geprüft... dies kann einen Moment dauern.',
    // Errors
    error_message: 'Die Website konnte nicht analysiert werden. Die URL ist möglicherweise ungültig, nicht erreichbar oder der Dienst ist vorübergehend nicht verfügbar. Bitte überprüfen Sie die URL und versuchen Sie es erneut.',
    error_unknown: 'Ein unbekannter Fehler ist aufgetreten.',
    error_title: 'Analyse fehlgeschlagen',
    // Dashboard
    dashboard_title: 'Prüfbericht für',
    download_pdf: 'PDF herunterladen',
    overall_scores: 'Gesamtbewertungen',
    performance: 'Leistung',
    accessibility: 'Barrierefreiheit',
    best_practices: 'Best Practices',
    seo: 'SEO',
    core_web_vitals: 'Core Web Vitals',
    lcp: 'Largest Contentful Paint',
    lcp_desc: 'Zeit, bis das größte Inhaltselement sichtbar wird.',
    cls: 'Cumulative Layout Shift',
    cls_desc: 'Misst die visuelle Stabilität der Seite.',
    inp: 'Interaction to Next Paint',
    inp_desc: 'Misst die Reaktionsfähigkeit der Seite auf Benutzerinteraktionen.',
    key_metrics: 'Schlüsselmetriken',
    fcp: 'First Contentful Paint',
    fcp_desc: 'Zeit, bis das erste Inhaltselement erscheint.',
    speed_index: 'Speed Index',
    speed_index_desc: 'Wie schnell Inhalte visuell angezeigt werden.',
    tti: 'Time to Interactive',
    tti_desc: 'Zeit, bis die Seite vollständig interaktiv ist.',
    tbt: 'Total Blocking Time',
    tbt_desc: 'Zeit, in der der Haupt-Thread blockiert war.',
    server_response_time: 'Server-Antwortzeit',
    server_response_time_desc: 'Zeit, die der Server zum Antworten benötigt (TTFB).',
    https: 'Verwendet HTTPS',
    https_desc: 'Gewährleistet eine sichere Verbindung.',
    crawlable: 'Ist Crawl-bar',
    crawlable_desc: 'Suchmaschinen können auf die Seite zugreifen.',
    mobile_friendly: 'Mobilfreundlich',
    mobile_friendly_desc: 'Hat ein Viewport-Meta-Tag für Mobilgeräte.',
    readable_fonts: 'Lesbare Schriftarten',
    readable_fonts_desc: 'Schriftgrößen sind groß genug für Lesbarkeit.',
    image_aspect_ratio: 'Korrekte Bild-Seitenverhältnisse',
    image_aspect_ratio_desc: 'Bilder haben korrekte Breiten-/Höhenattribute.',
    page_stats: 'Seitenstatistiken',
    total_page_size: 'Gesamtseitengröße',
    total_requests: 'Gesamtanfragen',
    js_execution_time: 'JS-Ausführungszeit',
    pass: 'Bestanden',
    fail: 'Fehlgeschlagen'
  }
};
